package GUI;

import eventpkg.QueueInterface;
import javax.swing.JOptionPane;
import model.Event;
import model.Person;
import model.Volunteer;
import personpkg.SLNode;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Thitsar Thway
 */
public class EventsGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventsGUI.class.getName());
    //for shared data
    private QueueInterface myQueue = Main.eventQueue;

    /**
     * Creates new form eventsGUI
     */
    public EventsGUI() {
        initComponents();
        //to fill combobox
        populateVolunteers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        venueLbl = new javax.swing.JLabel();
        assignedVolunteersLbl = new javax.swing.JLabel();
        assignedVolunteersCB = new javax.swing.JComboBox<>();
        titleTF = new javax.swing.JTextField();
        dateTF = new javax.swing.JTextField();
        venueTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayAllBtn = new javax.swing.JButton();
        frontBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        instructionLbl2 = new javax.swing.JLabel();
        assignMoreBtn = new javax.swing.JButton();
        instructionLbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomeLbl.setText("Events");

        titleLbl.setText("Title");

        dateLbl.setText("Date");

        venueLbl.setText("Venue");

        assignedVolunteersLbl.setText("Volunteers");

        assignedVolunteersCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addBtn.setText("Add Event");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayAllBtn.setText("See All Events");
        displayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBtnActionPerformed(evt);
            }
        });

        frontBtn.setText("See Upcoming");
        frontBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontBtnActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        backBtn.setText("Back to Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Remove Latest");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        instructionLbl2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructionLbl2.setForeground(new java.awt.Color(0, 0, 255));
        instructionLbl2.setText("select from the dropdown and click assign more volunteers.");

        assignMoreBtn.setText("Assign More Volunteers");
        assignMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMoreBtnActionPerformed(evt);
            }
        });

        instructionLbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructionLbl3.setForeground(new java.awt.Color(0, 0, 255));
        instructionLbl3.setText("To assign multiple volunteers,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dateLbl)
                                    .addComponent(venueLbl)
                                    .addComponent(titleLbl))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(venueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(assignMoreBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignedVolunteersLbl)
                                .addGap(18, 18, 18)
                                .addComponent(assignedVolunteersCB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(instructionLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(instructionLbl2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(welcomeLbl))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(frontBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(displayAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(venueLbl)
                            .addComponent(assignMoreBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLbl)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignedVolunteersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignedVolunteersLbl)
                    .addComponent(instructionLbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLbl2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frontBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayAllBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainGUI myGUI = new MainGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //grab text fields
        String title = titleTF.getText();
        String date = dateTF.getText();
        String venue = venueTF.getText();
        String selected = (String) assignedVolunteersCB.getSelectedItem();
        //  Volunteer selected = (Volunteer) assignedVolunteersCB.getSelectedItem();
        if (!title.isEmpty() || !date.isEmpty() || !venue.isEmpty()) {
            //create instance
            Event e = new Event();
            e.setTitle(title);
            e.setDate(date);
            e.setVenue(venue);
            if (selected != null) {
                e.getAssignedVolunteers().add(selected);
            }
            //add to queue
            myQueue.enqueue(e);
            displayTA.setText(myQueue.printQueue());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please fill out the text fields.");
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void displayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBtnActionPerformed
        // TODO add your handling code here:
        displayTA.setText("");
        //check if empty
        if (myQueue.isEmpty()) {
            displayTA.setText("There are no scheduled events.");
        } else
            displayTA.setText(myQueue.printQueue());
    }//GEN-LAST:event_displayAllBtnActionPerformed

    private void frontBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontBtnActionPerformed
        // TODO add your handling code here:
        //check if empty
        if (myQueue.isEmpty()) {
            displayTA.setText("There are no upcoming events.");
        } else {
            //return element at the front of queue
            Event nextEvent = (Event) myQueue.frontElement();
            displayTA.setText("\nNext Event Title: " + nextEvent.getTitle() + "\nDate: " + nextEvent.getDate() + "\nVenue: " + nextEvent.getVenue());
        }
    }//GEN-LAST:event_frontBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        //check if empty
        if (myQueue.isEmpty()) {
            displayTA.setText("There are no upcoming events.");
        } else {
            //dequeue to traverse through queue
            Event nextEvent = (Event) myQueue.dequeue();
            displayTA.setText("\nNext Event Title: " + nextEvent.getTitle() + "\nDate: " + nextEvent.getDate() + "\nVenue: " + nextEvent.getVenue());
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void assignMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMoreBtnActionPerformed
        // TODO add your handling code here:
        //get volunteer from combobox
        String selectedVolunteer = (String) assignedVolunteersCB.getSelectedItem();
        //check if combobox is not populated
        if (selectedVolunteer == null) {
            JOptionPane.showMessageDialog(rootPane, "No volunteers available. Please add volunteers first.");
            return;
        }
        //get event title
        String eventTitle = JOptionPane.showInputDialog("Enter the title of the event to assign to:");
        if (eventTitle == null || eventTitle.isEmpty()) {
            return;
        }
        //find event title in queue
        for (int i = 0; i < myQueue.size(); i++) {
            //dequeue each event to find title match
            Event e = (Event) myQueue.dequeue();
            //add to assigned volunteers arraylist if found
            if (e.getTitle().equalsIgnoreCase(eventTitle)) {
                e.getAssignedVolunteers().add(selectedVolunteer);
                //re-enqueue updated event
                myQueue.enqueue(e);
                // re-enqueue remaining events
                for (int j = i + 1; j < myQueue.size(); j++) {
                    myQueue.enqueue(myQueue.dequeue());
                }
                JOptionPane.showMessageDialog(rootPane, selectedVolunteer + " assigned to " + eventTitle);
                return;
            }
            myQueue.enqueue(e);
        }
        JOptionPane.showMessageDialog(rootPane, "Event not found.");
    }//GEN-LAST:event_assignMoreBtnActionPerformed
    private void populateVolunteers() {
        //clear before populating to remove default values and avoid duplicates
        assignedVolunteersCB.removeAllItems();
        //loop personList to find volunteers
        for (int i = 1; i <= Main.personList.size(); i++) {
            SLNode node = (SLNode) Main.personList.get(i);
            Person p = (Person) node.getElement();
            if (p instanceof Volunteer) {
                //add volunteer names to combobox
                assignedVolunteersCB.addItem(p.getName());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EventsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton assignMoreBtn;
    private javax.swing.JComboBox<String> assignedVolunteersCB;
    private javax.swing.JLabel assignedVolunteersLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton displayAllBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton frontBtn;
    private javax.swing.JLabel instructionLbl2;
    private javax.swing.JLabel instructionLbl3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTF;
    private javax.swing.JLabel venueLbl;
    private javax.swing.JTextField venueTF;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
