/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import model.Person;
import model.Resident;
import model.Volunteer;
import personpkg.LinearListInterface;
import personpkg.MySLL;
import personpkg.SLNode;

/**
 *
 * @author Thitsar Thway
 */
public class PersonsGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonsGUI.class.getName());
    //for shared data
    private LinearListInterface myList = Main.personList;    
    /**
     * Creates new form ResidentsGUI
     */
    public PersonsGUI() {
        initComponents();
        //select volunteer at start up
        volunteerRB.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleBg = new javax.swing.ButtonGroup();
        welcomeLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        displayAllBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        volunteerRB = new javax.swing.JRadioButton();
        residentRB = new javax.swing.JRadioButton();
        idLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        availabilityLbl = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        availabilityTF = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        displaySelectedBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcomeLbl.setText("Manage Persons");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        displayAllBtn.setText("Display All");
        displayAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Find By Id");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        roleBg.add(volunteerRB);
        volunteerRB.setText("Volunteer");
        volunteerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerRBActionPerformed(evt);
            }
        });

        roleBg.add(residentRB);
        residentRB.setText("Resident");
        residentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentRBActionPerformed(evt);
            }
        });

        idLbl.setText("Id");

        nameLbl.setText("Name");

        phoneLbl.setText("Phone");

        availabilityLbl.setText("Availability");

        backBtn.setText("Back to Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        displaySelectedBtn.setText("Display Selected Role");
        displaySelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaySelectedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeLbl)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(availabilityLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(availabilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(phoneLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nameLbl)
                                            .addComponent(idLbl))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayAllBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displaySelectedBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volunteerRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(residentRB)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volunteerRB)
                    .addComponent(residentRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLbl)
                    .addComponent(displaySelectedBtn))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availabilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availabilityLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backBtn)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //return to MainGUI
        MainGUI myGUI = new MainGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void volunteerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerRBActionPerformed
        // TODO add your handling code here:
        //show the availability section
        availabilityLbl.setVisible(true);
        availabilityTF.setVisible(true);
    }//GEN-LAST:event_volunteerRBActionPerformed

    private void residentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentRBActionPerformed
        // TODO add your handling code here:       
        //hide the availability section
        availabilityLbl.setVisible(false);
        availabilityTF.setVisible(false);
    }//GEN-LAST:event_residentRBActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try{
        //grab text from text fields
        int id = Integer.parseInt(idTF.getText());
        String name = nameTF.getText();
        String phone = phoneTF.getText();
        
        if (volunteerRB.isSelected()) {
            String availability = availabilityTF.getText();
            
            //check empty text fields
            if(name.isEmpty()||phone.isEmpty()||availability.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Please fill out the text fields.");
                return;
            }
            
            Volunteer v = new Volunteer(id, name, phone, availability);
            myList.add(v);
            
        } else if (residentRB.isSelected()) {
            
            //check empty text fields
            if(name.isEmpty()||phone.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Please fill out the text fields.");
                return;
            }
            
            Resident r = new Resident(id, name, phone);
            myList.add(r);
            
        } else {
            //check option button not selected
            JOptionPane.showMessageDialog(rootPane, "Please select a role.");
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "Person added successfully.");
        
        //clear text fields
        idTF.setText("");
        nameTF.setText("");
        phoneTF.setText("");
        availabilityTF.setText("");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Please enter a number for the id");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllBtnActionPerformed
        // clear display area
        displayTA.setText("");
        //check empty list
        if(myList.isEmpty()){
            displayTA.setText("There are no entries in the list.");
        }
        //loop and show entries
        for (int i = 1; i <= myList.size(); i++) {
            SLNode node = (SLNode) myList.get(i);
            Person p = (Person) node.getElement();
            displayTA.append(p.getInfo() + "\n");
        }
    }//GEN-LAST:event_displayAllBtnActionPerformed

    private void displaySelectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaySelectedBtnActionPerformed
        // clear display area
        displayTA.setText("");
        //check empty list
        if(myList.isEmpty()){
            displayTA.setText("There are no entries in the list.");
        }
        //loop and show entries according to role type
        for (int i = 1; i <= myList.size(); i++) {
            SLNode node = (SLNode) myList.get(i);
            Person p = (Person) node.getElement();
            if (volunteerRB.isSelected() && p instanceof Volunteer) {
                displayTA.append(p.getInfo() + "\n");
            } else if (residentRB.isSelected() && p instanceof Resident) {
                displayTA.append(p.getInfo() + "\n");
            }
        }
    }//GEN-LAST:event_displaySelectedBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            //get the id to delete
            int deleteId = Integer.parseInt(JOptionPane.showInputDialog("Please enter id of person to remove"));
            //find id in list
            for(int i = 1;i<=myList.size();i++){
                SLNode node = (SLNode) myList.get(i);
                Person p = (Person) node.getElement();
                if(p.getId()==deleteId){
                    myList.remove(i);
                    JOptionPane.showMessageDialog(rootPane, "Person with id "+deleteId+ " was removed successfully.");
                    return;
                }
            }
            //check not found
            JOptionPane.showMessageDialog(rootPane, "Id not found.");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Please enter a number for the id.");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try {
        //get the id to update
        int updateId = Integer.parseInt(JOptionPane.showInputDialog("Enter ID of person to update:"));
        //find id in list
        for (int i = 1; i <= myList.size(); i++) {
            SLNode node = (SLNode) myList.get(i);
            Person p = (Person) node.getElement();
            
            if (p.getId() == updateId) {
                //get name
                String newName = JOptionPane.showInputDialog("Enter new name:", p.getName());
                //check empty input
                if (newName == null || newName.isEmpty()) return;
                //get phone
                String newPhone = JOptionPane.showInputDialog("Enter new phone:", p.getPhone());
                //check empty input
                if (newPhone == null || newPhone.isEmpty()) return;
                //set name and phone
                p.setName(newName);
                p.setPhone(newPhone);
                //if volunteer, set availability
                if (p instanceof Volunteer volunteer) {
                    String newAvailability = JOptionPane.showInputDialog("Enter new availability:", volunteer.getAvailability());
                    if (newAvailability == null || newAvailability.isEmpty()) return;
                    volunteer.setAvailability(newAvailability);
                }
                
                JOptionPane.showMessageDialog(rootPane, "Person updated successfully.");
                return;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Id not found.");
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Please enter a number for the id.");
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try{
            //get id to search
            int searchId = Integer.parseInt(JOptionPane.showInputDialog("Enter id of person to search"));
            //find in list
            for(int i=1;i<=myList.size();i++){
                SLNode node = (SLNode) myList.get(i);
                Person p = (Person) node.getElement();
                if(p.getId()==searchId){
                    displayTA.setText(p.getInfo());
                    return;
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Id not found");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Please enter a number for the id.");

        }
    }//GEN-LAST:event_searchBtnActionPerformed
    //for volunteer combobox in eventsGUI
//    public static MySLL getList() {
//        return myList;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PersonsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel availabilityLbl;
    private javax.swing.JTextField availabilityTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayAllBtn;
    private javax.swing.JButton displaySelectedBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JRadioButton residentRB;
    private javax.swing.ButtonGroup roleBg;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JRadioButton volunteerRB;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
